<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260318102538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE addresses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, postal_code INT NOT NULL, province VARCHAR(255) NOT NULL, country_code VARCHAR(255) NOT NULL, iduser_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FCA7516786A81FB ON addresses (iduser_id)');
        $this->addSql('CREATE TABLE items_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, price DOUBLE PRECISION NOT NULL, product_id INT DEFAULT NULL, idorder_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F1F559234584665A ON items_order (product_id)');
        $this->addSql('CREATE INDEX IDX_F1F55923274A2535 ON items_order (idorder_id)');
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, shipping_number INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, shipped_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, invoice_path VARCHAR(255) DEFAULT NULL, total_price DOUBLE PRECISION NOT NULL, iduser_id INT DEFAULT NULL, addresses_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5299398786A81FB ON "order" (iduser_id)');
        $this->addSql('CREATE INDEX IDX_F52993985713BC80 ON "order" (addresses_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_published BOOLEAN NOT NULL, thumbnail VARCHAR(255) NOT NULL, weight DOUBLE PRECISION NOT NULL, height DOUBLE PRECISION NOT NULL, length DOUBLE PRECISION NOT NULL, price DOUBLE PRECISION NOT NULL, promo_price DOUBLE PRECISION DEFAULT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, priority INT NOT NULL, stock INT NOT NULL, sku VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE product_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE product_category_product (product_category_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (product_category_id, product_id))');
        $this->addSql('CREATE INDEX IDX_9A1E202FBE6903FD ON product_category_product (product_category_id)');
        $this->addSql('CREATE INDEX IDX_9A1E202F4584665A ON product_category_product (product_id)');
        $this->addSql('CREATE TABLE product_category_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, product_category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1DAAB487BE6903FD ON product_category_translation (product_category_id)');
        $this->addSql('CREATE TABLE product_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_url VARCHAR(255) NOT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8263FFCE4584665A ON product_images (product_id)');
        $this->addSql('CREATE TABLE product_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, composition VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1846DB704584665A ON product_translation (product_id)');
        $this->addSql('CREATE TABLE support (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, reply VARCHAR(255) NOT NULL, iduser_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8004EBA5786A81FB ON support (iduser_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, siren_number INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE addresses ADD CONSTRAINT FK_6FCA7516786A81FB FOREIGN KEY (iduser_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE items_order ADD CONSTRAINT FK_F1F559234584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE items_order ADD CONSTRAINT FK_F1F55923274A2535 FOREIGN KEY (idorder_id) REFERENCES "order" (id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398786A81FB FOREIGN KEY (iduser_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993985713BC80 FOREIGN KEY (addresses_id) REFERENCES addresses (id)');
        $this->addSql('ALTER TABLE product_category_product ADD CONSTRAINT FK_9A1E202FBE6903FD FOREIGN KEY (product_category_id) REFERENCES product_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_category_product ADD CONSTRAINT FK_9A1E202F4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_category_translation ADD CONSTRAINT FK_1DAAB487BE6903FD FOREIGN KEY (product_category_id) REFERENCES product_category (id)');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT FK_8263FFCE4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_translation ADD CONSTRAINT FK_1846DB704584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE support ADD CONSTRAINT FK_8004EBA5786A81FB FOREIGN KEY (iduser_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE addresses DROP CONSTRAINT FK_6FCA7516786A81FB');
        $this->addSql('ALTER TABLE items_order DROP CONSTRAINT FK_F1F559234584665A');
        $this->addSql('ALTER TABLE items_order DROP CONSTRAINT FK_F1F55923274A2535');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398786A81FB');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993985713BC80');
        $this->addSql('ALTER TABLE product_category_product DROP CONSTRAINT FK_9A1E202FBE6903FD');
        $this->addSql('ALTER TABLE product_category_product DROP CONSTRAINT FK_9A1E202F4584665A');
        $this->addSql('ALTER TABLE product_category_translation DROP CONSTRAINT FK_1DAAB487BE6903FD');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCE4584665A');
        $this->addSql('ALTER TABLE product_translation DROP CONSTRAINT FK_1846DB704584665A');
        $this->addSql('ALTER TABLE support DROP CONSTRAINT FK_8004EBA5786A81FB');
        $this->addSql('DROP TABLE addresses');
        $this->addSql('DROP TABLE items_order');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_category');
        $this->addSql('DROP TABLE product_category_product');
        $this->addSql('DROP TABLE product_category_translation');
        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE product_translation');
        $this->addSql('DROP TABLE support');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
