<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260615081233 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        // NB : invoice_number_seq est une séquence gérée manuellement (utilisée en
        // SQL brut par InvoiceService) ; make:migration ne la voit pas dans le schéma
        // Doctrine et voulait la supprimer — on ne touche pas à cette séquence.
        $this->addSql('ALTER TABLE site_settings ADD value_ar TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE site_settings ADD value_zh TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE site_settings ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE site_settings ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_site_settings_key RENAME TO UNIQ_E9081F1F5FA1E697');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE site_settings DROP value_ar');
        $this->addSql('ALTER TABLE site_settings DROP value_zh');
        $this->addSql('ALTER TABLE site_settings ALTER id SET DEFAULT nextval(\'site_settings_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE site_settings ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_e9081f1f5fa1e697 RENAME TO uniq_site_settings_key');
    }
}
