<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create carousel_slide table (hero carousel managed from EasyAdmin)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE carousel_slide (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, cta_text VARCHAR(100) DEFAULT NULL, cta_url VARCHAR(255) DEFAULT NULL, image_filename VARCHAR(255) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE carousel_slide');
    }
}
